//1. What is the necessity to create a separate file after having an API key?
// a) To hold configuration information
// b) To hold key details
// c) To hold URL details
// d) To hold the speed of the process

//Answer: a
// Explanation: An application programming interface key (API key) is a code passed in by computer programs calling an application programming interface (API) to identify the calling program, its developer, or its user to the Web site. Once you have an API key you should create a separate file to hold all of the configuration information that you will need to share between processes.

//How many parameters does the API accept?
// a) 5
// b) 6
// c) 7
// d) 8

//Answer: d
// Explanation: Parameters are options you can pass with the endpoint (such as specifying the response format or the amount returned) to influence the response. The API accepts a total of 8 parameters namely:
// url
// location
// runs
// fvonly
// private
// block
// f
// k

//3. What is not the purpose of the parameter location?
// a) Specifies agent location
// b) Specifies speed
// c) Specifies browser
// d) Specifies block

// Answer: d
// Explanation: The window.location object can be used to get the current page address (URL) and to redirect the browser to a new page. The parameter location specifies the agent location, speed and browser to use for the test, formatted as location.browser:location.

// 5. How many reserved words are there in JavaScript?
// a) 63
// b) 54
// c) 68
// d) 90

// Answer: a
// Explanation: Keywords are reserved words in JavaScript which you cannot use to name the variables labels or function names. There are a total of 63 reserved words in JavaScript.