// 7. Which of the following method loads a new document?
// a) location.new()
// b) loadnew()
// c) location.load()
// d) location.assign()

// Answer: d
// Explanation: The window.location object can be written without the window prefix.
// Some examples are window.location.href returns the href (URL) of the current page
// window.location.hostname returns the domain name of the web host.


// 8. Which of the following method will wait for certain milliseconds to execute a specified method?
// a) setInterval()
// b) setTimeout()
// c) setmilli()
// d) setseconds()


// Answer: a
// Explanation: The setInterval() method calls a function or evaluates an expression at specified intervals (in milliseconds). The setInterval() method will wait a specified number of milliseconds, and then execute a specified function, and it will continue to execute the function, once at every given time-interval.